//
//  ResourcesSceneRouter.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResourcesSceneRoutingLogic {
    func showResourcesError(_ message: String)
}

class ResourcesSceneRouter: ResourcesSceneRoutingLogic {
    weak var source: ResourcesSceneViewController?
    
    func showResourcesError(_ message: String) {
        source?.showAlert(title: "Erro", message: message)
    }
}
