//
//  ResourcesScenePresenter.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ResourcesScenePresenterInput = ResourcesSceneInteractorOutput
typealias ResourcesScenePresenterOutput = ResourcesSceneViewControllerInput

class ResourcesScenePresenter: ResourcesScenePresenterInput {
    weak var viewController: ResourcesScenePresenterOutput?
    
    func errorOnGetResources(errorMessage: String) {
        viewController?.showErrorOnGetResources(errorMessage)
    }
    
    func didGetResources(_ resources: [Resource]) {
        viewController?.updateResources(resources)
    }
}
