//
//  ResourcesSceneInteractor.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ResourcesSceneInteractorInput = ResourcesSceneViewControllerOutput
protocol ResourcesSceneInteractorOutput {
    func errorOnGetResources(errorMessage: String)
    func didGetResources(_ resources: [Resource])
}

class ResourcesSceneInteractor: ResourcesSceneInteractorInput {
    var presenter: ResourcesSceneInteractorOutput?
    
    func getResources() {
        ReqressAPI.shared.getResources { [weak self] resources, error in
            if let error = error {
                self?.presenter?.errorOnGetResources(errorMessage: error.localizedDescription)
            } else if let resources = resources {
                self?.presenter?.didGetResources(resources)
            }
        }
    }
}
