//
//  ResourcesSceneViewController.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResourcesSceneViewControllerInput: AnyObject {
    func showErrorOnGetResources(_ message: String)
    func updateResources(_ resources: [Resource])
}

protocol ResourcesSceneViewControllerOutput {
    func getResources()
}

class ResourcesSceneViewController: UITableViewController, ResourcesSceneViewControllerInput {
    var resources = [Resource]() {
        didSet {
            tableView.reloadData()
        }
    }
    var selectedCell: IndexPath?
    
    var interactor: ResourcesSceneViewControllerOutput?
    var router: ResourcesSceneRoutingLogic?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        interactor?.getResources()
    }
    
    private func setupTableView() {
        let nib = UINib(nibName: "ResourcesTableViewCell", bundle: nil)
        tableView.register(nib, forCellReuseIdentifier: "resourcesCell")
        tableView.rowHeight = 90
        tableView.tableHeaderView = getTableViewHeader()
    }
    
    private func getTableViewHeader() -> UIView {
        let headerView = UIView(frame: CGRect(x: 0, y: 0, width: tableView.frame.width, height: 60))
        let label = UILabel()
        label.text = "Cores Pantone"
        label.font = label.font.withSize(20)
        headerView.addSubview(label)
        label.centerOnSuperview()
        return headerView
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return resources.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "resourcesCell") as! ResourcesTableViewCell
        cell.resource = resources[indexPath.row]
        return cell
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if selectedCell == indexPath {
            return 130
        }
        return 90
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        selectedCell = indexPath
        UIView.animate(withDuration: 1) {
            tableView.beginUpdates()
            tableView.endUpdates()
        }
    }
    
    func showErrorOnGetResources(_ message: String) {
        router?.showResourcesError(message)
    }
    
    func updateResources(_ resources: [Resource]) {
        self.resources = resources
    }
}
