//
//  RegisterSceneRouter.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterSceneRoutingLogic {
    func showNotValidAlert()
    func showRegisterError(_ message: String)
    func showTableScene()
}

class RegisterSceneRouter: RegisterSceneRoutingLogic {
    weak var source: RegisterSceneViewController?
    
    func showNotValidAlert() {
        source?.showAlert(title: "Campos Inválidos", message: "Preencha corretamente todos os campos")
    }
    
    func showRegisterError(_ message: String) {
        source?.showAlert(title: "Erro ao registrar usuário", message: message)
    }
    
    func showTableScene() {
        print("registrou com sucesso")
    }
}
