//
//  RegisterSceneViewController.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterSceneViewControllerInput: AnyObject {
    func showDateFormatted(_ dateString: String)
    func showNotValidAlert()
    func showRegisterError(_ message: String)
    func showTableScene()
}

protocol RegisterSceneViewControllerOutput: AnyObject {
    func validateFields(_ textFields: [UITextField])
    func formatDate(date: Date)
}

class RegisterSceneViewController: UIViewController {
    // MARK: - IBOutlets
    @IBOutlet var textFields: [UITextField]!
    @IBOutlet weak var dateTextField: UITextField!
    
    // MARK: - Views
    let datePickerView = UIDatePicker()
    
    // MARK: Variables
    var interactor: RegisterSceneViewControllerOutput?
    var router: RegisterSceneRoutingLogic?
    
    // MARK: - Life Cycke
    override func viewDidLoad() {
        super.viewDidLoad()
        setupDatePicker()
    }
    
    // MARK: - IBActions
    @IBAction func register() {
        interactor?.validateFields(textFields)
    }
    
    // MARK: - Private Methods
    private func setupDatePicker() {
        datePickerView.datePickerMode = .date
        datePickerView.preferredDatePickerStyle = .wheels
        datePickerView.addTarget(self, action: #selector(self.insertDateOnTextField), for: .valueChanged)
        dateTextField.inputView = datePickerView
    }
    
    @objc private func insertDateOnTextField() {
        interactor?.formatDate(date: datePickerView.date)
    }
}

extension RegisterSceneViewController: RegisterSceneViewControllerInput {
    func showDateFormatted(_ dateString: String) {
        self.dateTextField.text = dateString
    }
    
    func showNotValidAlert() {
        router?.showNotValidAlert()
    }
    
    func showRegisterError(_ message: String) {
        router?.showRegisterError(message)
    }
    
    func showTableScene() {
        router?.showTableScene()
    }
}
