//
//  RegisterScenePresenter.swift
//  RegisterApp
//
//  Created by Curitiba01 on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias RegisterScenePresenterInput = RegisterSceneInteractorOutput
typealias RegisterScenePresenterOutput = RegisterSceneViewControllerInput

class RegisterScenePresenter: RegisterScenePresenterInput {
    weak var viewController: RegisterScenePresenterOutput?
    
    func didFormatDate(_ dateString: String) {
        viewController?.showDateFormatted(dateString)
    }
    
    func registerDidFail(errorMessage: String) {
        viewController?.showRegisterError(errorMessage)
    }
    
    func registerDidSucceed() {
        viewController?.showTableScene()
    }
    
    func fieldsNotValid() {
        viewController?.showNotValidAlert()
    }
}
